# Service ID
set_peakshaving:
  # Service name as shown in UI
  name: Set Peak Shaving
  # Description of the service
  description: Sets Peak Shaving Mode, battery capacity limit and end time.
  # Battery capacity limit and end time can just be set, if the selected mode is "Manual"
  # Different fields that your service accepts
  fields:
    # Key of the field
    mode:
      # Whether field is required (default = false)
      required: true
      # Field name as shown in UI
      name: Peak Shaving Mode
      # Description of the field
      description: DEACTIVATED = Peak Shaving is disabled, MANUAL = You can set the parameter (battery capacity, end time), AUTO = Peak Shaving is in automatic mode. Battery capacity and end time will be ignored.
      #Example value
      example: "AUTO"
      #Default value
      default: "AUTO"
      # Options
      selector:
        select:
          mode: "dropdown"
          translation_key: "set_peakshaving_mode_options"
          options:
           - DEACTIVATED
           - MANUAL
           - AUTO
    capacity:
      required: true
      name: Battery capacity limit
      description: Temporarily limits the capacity of the battery storage, so that the remaining capacity can be used for potential losses due to the export limit.
      example: "10"
      default: "10"
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    end_time:
      required: true
      name: End time
      description: Time of the day on which the capacity limitation should switch off again.
      example: "15:00:00"
      default: "15:00:00"
      selector:
        time:
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
